[package]
name = "vox-rs"
version = "0.1.0"
authors = ["Oguzhan YAGCI <oyagci@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "0.22.0"
vulkano-win = "0.22.0"
winit = "0.24.0"